### ISSUE TITLE
It's just me or it doesn't currently work?

### ISSUE THREAD

**Issue by rodrigograca31** [ExPixel/Cling#1]
It's not working on my chrome... Latest version and no plugins....

**Comment by rodrigograca31** [comment]
Today is working on one of my chrome installations, but when I go back to the top the video is black....

**Comment by ExPixel** [comment]
Probably some changes to youtube that I haven't kept up with. I've been thinking about rewriting this anyway.

**Comment by rodrigograca31** [comment]
It would be cool if you could fix it :)

There's also another problem: the plugin shows up on all youtube pages... it shouldn't...

**Comment by ExPixel** [comment]
Alright I've fixed a lot of the issues I noticed myself. The issue where it wasn't working on one of your installations of Chrome is one I wasn't really able to reproduce myself but hopefully the full rewrite did something that fixes it. The update should be live in about an hour. I'll close this issue for now and if the same problem crops up, feel free to reopen it.

**Comment by rodrigograca31** [comment]
Thanks @ExPixel 
How do extensions get updated? I need to restart the browser/PC?
(Because I'm always using chrome, and chrome is always on the background...)

**Comment by rodrigograca31** [comment]
It looks like everything is working!
Nice job! And nice transition/effect ;)
